- name: Install Logstash in CentOS
  yum:
    name: /tmp/logstash-7.8.0.rpm
    state: present
  when: ansible_distribution == "CentOS"

- name: Start Logstash
  service:
    name: logstash
    state: restarted
